### ISSUE TITLE
Support Unicode in usernames

### ISSUE THREAD

**Issue by steigr** [coreos/dex#1006]
I've added a user-entry in DEX via local-user yaml-file:
```
staticPasswords:
  - email: "mx@example.com"
    hash: "..."
    username: "Max Süß"
    userID: "0815"
```

After login in Tectonic-Console `ü` and `ß` were trashed . Trying `&ouml;` and `&szlig;` didn't fix the issue.
