### ISSUE TITLE
GitHub connector - userInOrg fails when user.name != user.login

### ISSUE THREAD

**Issue by so0k** [coreos/dex#1032]
If your user name does not match your login name, the `userInOrg` call returns 404 and fails the login

https://sourcegraph.com/github.com/coreos/dex/-/blob/connector/github/github.go#L523-524

Not sure if this is an issue with dex-example app or dex GitHub connector

How to reproduce:

- Create GitHub OAuth2 app for Dex
- Deploy Dex with GitHub connector and `staticClients` "example-app"
- Deploy example dex-app with dex as it's oidc issuer
- Set up GitHub Name differently from GitHub login
- Log in and ask `groups` as an additional scope

Dex debug logs:

<details>

```
# sample-app without requesting "groups" scope
time="2017-08-17T08:43:28Z" level=info msg="login successful: connector \"github\", username=\"Vincent De Smet\", email=\"vincent.***@***.com\", groups=[]"

# sample-app requesting "groups" scope (user.name = "Vincent De Smet", GitHub user = "so0k")
time="2017-08-17T08:49:05Z" level=debug msg="github: user \"Vincent De Smet\" not in org \"my-org\"" connector=GitHub
time="2017-08-17T08:49:05Z" level=error msg="Failed to authenticate: github: user \"Vincent De Smet\" not in required orgs or teams"

# after changing name
# sample-app requesting "groups" scope (user.name == github user == "so0k")
time="2017-08-17T08:57:01Z" level=debug msg="github: user \"so0k\" in org \"my-org\" team \"DevOps\"" connector=GitHub
time="2017-08-17T08:57:01Z" level=info msg="login successful: connector \"github\", username=\"so0k\", email=\"vincent.***@***.com\", groups=[\"my-org:DevOps\"]"
```
</details>

**Comment by so0k** [comment]
Dex GitHub connector config:

```yaml
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: "https://dex.example.com/callback"
    orgs:
      - name: my-org
        teams:
        - DevOps
```
