### ISSUE TITLE
GitHub connector - verified emails required for GitHub Enterprise

### ISSUE THREAD

**Issue by ChienHuey** [coreos/dex#1033]
Set up the GitHub connector to connect to our GitHub Enterprise server. The authentication fails with the following message:

`time="2017-08-17T03:57:33Z" level=error msg="Failed to authenticate: github: get user: github: user has no verified, primary email"`

My config is as follows:

```
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: https://dex.thor.us-east-1.k8.clusters.xogrp.com/callback
    orgs:
    - name: DevOps
    - name: Shared
    - name: LocalPartners
    hostName: <REDACTED - url of our GitHub Enterprise server>
```

GitHub Enterprise does not support verified emails. Is there a config setting that I'm not aware of?
