### ISSUE TITLE
OIDC connector - failed to open connector google

### ISSUE THREAD

**Issue by ChienHuey** [coreos/dex#1034]
Trying to set up authentication to Google running dex on Kubernetes. Getting this error when trying to start the dex service:

`failed to initialize server: server: Failed to open connector google: failed to open connector: failed to create connector google: failed to get provider: Get /.well-known/openid-configuration: unsupported protocol scheme ""`

This is my config:

```
issuer: https://accounts.google.com
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
connectors:
- type: oidc
  id: google
  name: Google
  config:
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET
    redirectURI: https://dex.thor.us-east-1.k8.clusters.xogrp.com/callback
    hostedDomains:
    - $GOOGLE_HOSTED_DOMAIN
oauth2:
  skipApprovalScreen: true
```
