### ISSUE TITLE
Errors on adding multiple ldap connectors to Tectonic Identity config map 

### ISSUE THREAD

**Issue by anuiq** [coreos/dex#1053]
Hello 

I have a business need to add two LDAP connectors for our tectonic cluster. We have local and international users which need to be added. I was told by guys at Coreos that I should be able to add two connectors but that seems to give me trouble. When I add one, it works very well however both of them break when I add two ldap connectors. Both of them start giving me internal server error logs which I have below. There are no logs anywhere else that can help me understand what might be breaking. 

This is the new-tectonic-config.yaml 

```
    connectors:
      - name: ldap-DS
        id: tectonic-ldap
        type: ldap
        config:
          host: 'ldap.pdx.ds.adp.com:389'
          bindDN: cloudplatform@ds
          bindPW: JahS1MLtx07
          userSearch:
            baseDN: 'dc=ds,dc=ad,dc=adp,dc=com'
            filter: ''
            username: mail
            idAttr: sAMAccountName
            emailAttr: mail
            nameAttr: name
          groupSearch:
            baseDN: 'dc=ds,dc=ad,dc=adp,dc=com'
            filter: (objectClass=group)
            userAttr: DN
            groupAttr: member
            nameAttr: name
          insecureNoSSL: 
      - name: ldap-DSI
        id: tectonic-ldap-dsi
        type: ldap
        config:
          host: 'ldap.pdx.dsi.adp.com:389'
          bindDN: cloudplatform@ds
          bindPW: JahS1MLtx07
          userSearch:
            baseDN: 'dc=dsi,dc=ad,dc=adp,dc=com'
            filter: ''
            username: mail
            idAttr: sAMAccountName
            emailAttr: mail
            nameAttr: name
          groupSearch:
            baseDN: 'dc=dsi,dc=ad,dc=adp,dc=com'
            filter: (objectClass=group)
            userAttr: DN
            groupAttr: member
            nameAttr: name
          insecureNoSSL: true
```

I don't even see any logs on the pods other than 

```
Logs are currently unavailableM385.591,106.379h1.474v6.966l-0.066,3.148c1.641-1.373,3.583-2.512,5.559-2.512
              c4.287,0,6.432,3.215,6.432,8.206c0,5.459-3.316,8.675-7.102,8.675c-1.54,0-3.315-0.737-4.822-1.909h-0.066l-0.168,1.507h-1.239
              V106.379z M391.821,129.556c3.249,0,5.594-3.015,5.594-7.368c0-3.952-1.407-6.899-5.092-6.899c-1.607,0-3.349,0.938-5.258,2.646
              v9.546C388.84,128.986,390.581,129.556,391.821,129.556z"/>
            <path fill="#243A4C" d="M403.178,136.422c1.977,0,3.316-1.809,4.119-4.254l0.436-1.406l-6.598-16.379h1.607l3.886,10.115
              c0.502,1.34,1.139,3.081,1.741,4.488h0.135c0.502-1.407,1.037-3.148,1.473-4.488l3.45-10.115h1.507l-6.363,18.087
              c-0.904,2.68-2.512,5.325-5.393,5.325c-0.603,0-1.205-0.134-1.641-0.335l0.334-1.307
              C402.207,136.288,402.709,136.422,403.178,136.422z"/>
            <path fill="#243A4C" d="M433.158,107.986c2.578,0,4.555,1.272,5.727,2.646l-0.904,1.005c-1.205-1.34-2.812-2.244-4.822-2.244
              c-4.823,0-7.838,3.852-7.838,9.981c0,6.129,2.981,10.081,7.703,10.081c2.278,0,3.986-0.904,5.594-2.713l0.904,0.972
              c-1.674,1.942-3.684,3.148-6.564,3.148c-5.426,0-9.244-4.455-9.244-11.488C423.713,112.374,427.531,107.986,433.158,107.986z"/>
            <path fill="#243A4C" d="M449.608,113.981c3.885,0,7.234,3.081,7.234,8.474c0,5.325-3.35,8.407-7.234,8.407
              c-3.853,0-7.201-3.082-7.201-8.407C442.406,117.063,445.755,113.981,449.608,113.981z M449.608,129.556
              c3.248,0,5.693-2.881,5.693-7.101c0-4.254-2.445-7.167-5.693-7.167c-3.25,0-5.661,2.913-5.661,7.167
              C443.947,126.675,446.358,129.556,449.608,129.556z"/>
            <path fill="#243A4C" d="M461.668,114.383h1.271l0.135,2.981h0.1c1.072-1.977,2.646-3.383,4.556-3.383
              c0.603,0,1.071,0.067,1.608,0.335l-0.336,1.34c-0.535-0.201-0.837-0.269-1.473-0.269c-1.441,0-3.148,1.105-4.389,4.12v10.952
              h-1.473V114.383z"/>
            <path fill="#243A4C" d="M477.612,113.981c3.818,0,6.163,2.713,6.163,7.436c0,0.401,0,0.804-0.067,1.206h-11.588
              c0.066,4.052,2.445,6.966,6.062,6.966c1.741,0,3.114-0.569,4.32-1.439l0.603,1.139c-1.272,0.77-2.713,1.574-5.058,1.574
              c-4.119,0-7.436-3.148-7.436-8.407S474.028,113.981,477.612,113.981z M482.367,121.483c0-4.119-1.842-6.229-4.722-6.229
              c-2.747,0-5.191,2.378-5.526,6.229H482.367z"/>
            <path fill="#243A4C" d="M486.758,119.34c0-6.966,3.785-11.354,9.111-11.354c5.291,0,9.076,4.388,9.076,11.354
              c0,7-3.785,11.522-9.076,11.522C490.543,130.862,486.758,126.34,486.758,119.34z M503.338,119.34c0-6.096-3.015-9.947-7.469-9.947
              c-4.488,0-7.503,3.852-7.503,9.947c0,6.13,3.015,10.115,7.503,10.115C500.323,129.455,503.338,125.47,503.338,119.34z"/>
            <path fill="#243A4C" d="M509.069,126.475c1.607,1.809,3.919,2.98,6.498,2.98c3.35,0,5.492-1.809,5.492-4.421
              c0-2.746-1.809-3.65-3.984-4.622l-3.35-1.507c-1.91-0.838-4.455-2.211-4.455-5.493c0-3.182,2.746-5.426,6.397-5.426
              c2.679,0,4.823,1.205,6.163,2.646l-0.904,1.038c-1.273-1.373-3.049-2.277-5.259-2.277c-2.914,0-4.856,1.541-4.856,3.952
              c0,2.546,2.211,3.517,3.818,4.254l3.35,1.474c2.444,1.105,4.621,2.479,4.621,5.861c0,3.383-2.779,5.929-7.066,5.929
              c-3.216,0-5.694-1.374-7.436-3.316L509.069,126.475z"/>
          </g>
        </svg>
      </div>
      <h2 class="heading">500</h2>
      <p>Internal Server Error</p>
      </form>
    </div>
  </body>
</html> 
```
This feels like a bug to me but I am not sure. The configs that I have added are correct. That is confirmed. Does anyone have any idea what might be going on ? 

Thank you
