### ISSUE TITLE
Tokens generated stops working after client-id changed in example-app

### ISSUE THREAD

**Issue by roffe** [coreos/dex#1075]
I am currently trying to make a login service to my K8S cluster using the example-app

However after changing client-id using --client-id the tokens i get is invalid and i observe the following error in the apiserver.

```
E0920 13:29:37.066988       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, [invalid bearer token, crypto/rsa: verification error, invalid bearer token, oidc: JWT claims invalid: invalid claims, 'aud' claim and 'client_id' do not match, aud=agi-login, client_id=example-app]]]
```

Even if i remove the old example-app entry from config, delete dex deployment & recreate it the error persists and it still mentions example-app.

If i add back example-app to the DEX config like the example below and run the example-app with client-id example-app it works again.

This leads me to think there might be some state in the cluster K8S database that is causing it.
as i don't know that much about the inner mechanics of DEX i'm kindly asking if someone knows what this might be due to?

Dex config
```
issuer: https://********/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: ********:10389

    # No TLS for this setup.
    insecureNoSSL: true

    userSearch:
      baseDN: ou=users,dc=********,dc=com
      filter: "(objectClass=inetOrgPerson)"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: ou=groups,dc=********,dc=com
      filter: "(&(objectClass=posixGroup)(cn=engineering))"

      # A user is a member of a group when their DN matches
      # the value of a "member" attribute on the group entity.
      userAttr: DN
      groupAttr: member

      # The group name should be the "cn" value.
      nameAttr: cn

staticClients:
- id: agi-login
  redirectURIs:
  - 'https://127.0.0.1:5556/callback'
  name: 'Cluster Login'
  secret: ********
- id: example-app
  redirectURIs:
  - 'https://127.0.0.1:5556/callback'
  name: 'example-app'
  secret: ********
```

Dex deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex
      containers:
      - image: quay.io/coreos/dex:v2.7.1
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

        ports:
        - name: https
          containerPort: 5556

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        env:
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: kube-system
spec:
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: 'true'
    ingress.kubernetes.io/use-port-in-redirects: 'true'
    kubernetes.io/ingress.class: haproxy
spec:
  tls:
  - hosts:
    - *********
    secretName: *********.tls
  rules:
  - host: *********
    http:
      paths:
      - path: /
        backend:
          serviceName: dex
          servicePort: 5556
```
