### ISSUE TITLE
Github: Groups not getting loaded when no org is specified in config

### ISSUE THREAD

**Issue by mrIncompetent** [coreos/dex#1102]
Dex is not fetching the groups when no org is specified in the config.
The groups scope is specified `&scope=openid%20email%20profile%20groups`

According to the Github Oauth Application in my private profile dex has the permission to read them.
Am i missing something here?

Version: 2.7.1

**Comment by devonbarrett** [comment]
Groups are only returned for orgs specified in the connector config.

>Dex queries the following organizations for group information if the
>"groups" scope is provided. Group claims are formatted as "(org):(team)".
>For example if a user is part of the "engineering" team of the "coreos"
>org, the group claim would include "coreos:engineering".

https://github.com/coreos/dex/blob/master/Documentation/github-connector.md#configuration

**Comment by mrIncompetent** [comment]
I was confused by the following code:
```
// groupsRequired returns whether dex requires GitHub's 'read:org' scope. Dex
// needs 'read:org' if 'orgs' or 'org' fields are populated in a config file.
// Clients can require 'groups' scope without setting 'orgs'/'org'.
func (c *githubConnector) groupsRequired(groupScope bool) bool {
	return len(c.orgs) > 0 || c.org != "" || groupScope
}
```

**Comment by ericchiang** [comment]
> Dex is not fetching the groups when no org is specified in the config.The groups scope is specified &scope=openid%20email%20profile%20groups

can you paste an example config (without your tokens)?

**Comment by mrIncompetent** [comment]
```yaml
issuer: https://***/dex
oauth2:
  skipApprovalScreen: true
  responseTypes:
  - code
  - token
  - id_token
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
connectors:
- config:
  clientID: ***
  clientSecret: ***
  issuer: https://accounts.google.com
  redirectURI: https://***/dex/callback
  id: google
  name: Google
  type: oidc
- config:
  clientID: ***
  clientSecret: ***
  redirectURI: https://***/dex/callback
  id: github
  name: GitHub
  type: github
staticClients:
- RedirectURIs:
  - https://***
  - http://localhost:8000
  id: myclient
  name: myclient
  secret: ***

```
