### ISSUE TITLE
issue integrating with Azure Active Directory 

### ISSUE THREAD

**Issue by tuwid** [coreos/dex#1150]
So i followed the steps using the Microsoft connector as follows:

```
 - type: microsoft
   # Required field for connector id.
   id: microsoft
   # Required field for connector name.
   name: Microsoft
   config:
     # Credentials can be string literals or pulled from the environment.
     clientID: XXXXXX
     clientSecret: XXXXXXXX
     redirectURI: http://callback_ip_somehwere-/dex/callback
     tenant: XXXXXXX
     groups:
       - developers
       - devops
```

Sorry, but we’re having trouble signing you in.We received a bad request.Additional technical information:
Correlation ID: XXXXXXX
Timestamp: 2017-12-15 20:21:16ZAADSTS70001: 
Application 'XXXXXXXXX' is not supported for this API version. | Additional technical information: | Correlation ID: XXXXXXXX | Timestamp: 2017-12-15 20:21:16Z | AADSTS70001: Application 'XXXXXXXXX' is not supported for this API version.

Is there any workarounds to this ? Should this be in a different connector implemented differently ?
