### ISSUE TITLE
Supported response types should be configured on a per-client basis

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#1156]
Right now we only have a global config value

```
oauth2:
   responseTypes: ["code", "token", "id_token"]
```

This should be local to the client

```
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  responseTypes: ["code", "token"]
```
