### ISSUE TITLE
LDAP password is stored in clear text ConfigMap

### ISSUE THREAD

**Issue by danilina-wsib** [coreos/dex#1158]
Currently, tectonic-identity stores a clear text LDAP password in a ConfigMap. This is not secure, a secret is probably a better way to store it.

**Comment by ericchiang** [comment]
Yep, we plan to address this with https://github.com/coreos/dex/issues/1099

**Comment by ericchiang** [comment]
Note that you can already store it as part of the environment variable. Fields in the `storage.config` blocks are expanded from the environment.

```
storage:
- type: ldap
  config:
    password: $PASSWORD
```
