### ISSUE TITLE
Configure SAML is not working with DEX

### ISSUE THREAD

**Issue by jenningsloy318** [coreos/dex#1169]
Hi All,

I just configure dex to integrated with my corp's IDP service, through the saml connector example, seems not working right now. dex will redirect to IDP, but no login screen appears.

**Backgroud**: 
     Our IDP service is co-work with UAA and provide the SSO for Cloud Foundry platform, the configureation need to involves trust configuration between them which is work perfectly. I want to use dex to replace UAA part with the IDP to provide the auth for kubernetes cluster in my testing env. 
    The trust configuration in both UAA and IDP is achieved by importing a metadata.xml file, in UAA side, it will add following four parameters: 

     - Single Sign-On URL (Redirect Binding)
     - Single Sign-On URL (Post Binding)
     - Single Logout URL (Redirect Binding)
     - Single Logout URL (Post Binding)
     
with same value: https://csc-devops-test.<IDP domain\>/saml2/idp/sso/csc-devops-test.<IDP domain\>
and plus an signning certificates of the IDP URL

in IDP part, sill several configuration is needed:

Field	|Description| value
-------|---|---
Name	|The entity ID of the service provider.| csc-devops-test-pt1.canary
Assertion Consumer Service Endpoint	|The SP's endpoint URL that receives the response with the SAML assertion from Identity Authentication.|https://csc-devops-test-pt1.<UAA domain\>/saml/SSO/alias/csc-devops-test-pt1.canary
Single Logout Endpoint	|The SP's endpoint URL that receives the logout response or request (for a multiple SPs scenario) from Identity Authentication for the termination of all current sessions.| it has two items configured,  both HTTP-Post and HTTP-Redirect are set to https://csc-devops-test-pt1.<UAA domain\>/saml/SingleLogout/alias/csc-devops-test-pt1.canary,
Signing Certificate|	A base64-encoded certificate used by the service provider to sign digitally SAML protocol messages sent to Identity Authentication.| certificates of the UAA url

**Dex Configuraion**:

as switched to DEX, I set the dex with following: 

```yaml
    issuer: https://dex.<my domain>
    storage:
      type: etcd
      config:
        # list of etcd endpoints we should connect to
        endpoints:
          - https://<etcd addr>:2379
        namespace: dex
        ssl:
          caFile: /etc/etcd/etcd-ca
          keyFile: /etc/etcd/etcd-key
          certFile: /etc/etcd/etcd-cert
    web:
      http: 0.0.0.0:5556
      #tlsCert: /etc/dex/tls/tls.crt
      #tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: saml
      # Required field for connector id.
      id: saml
      # Required field for connector name.
      name: SAML
      config:        
        ssoURL: https://csc-devops-test.<IDP domain>/saml2/idp/sso/csc-devops-test.<IDP domain>
        ca: /tmp/sci-ca.pem
        redirectURI: https://dex.<my domain>/callback
        entityIssuer: https://dex.<my domain>/callback
        ssoIssuer: https://csc-devops-test.<IDP domain>/saml2/idp/sso/csc-devops-test.<IDP domain>
        usernameAttr: name
        emailAttr: mail
        groupsAttr: Groups # optional        
        groupsDelim: ","        
    nameIDPolicyFormat: persistent
    #oauth2:
      #skipApprovalScreen: true
    logger:
      level: debug
      format: text 
    staticClients:
    - id: kubernetes
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      name: 'kubernetes'
    enablePasswordDB: true
```
on the IDP side,the name is set to `saml`,   three URL I set is `https://dex.<my domain>/callback`, and import the dex certificates.

**Problem**

When I use `example-app`  to get the token, it will redirect to the URL` https://csc-devops-test.<IDP domain>/saml2/idp/sso/csc-devops-test.<IDP domain>`， but neither login screen appears nor redirect to `https://dex.<my domain>/callback`, just gave me an error 
![image](https://user-images.githubusercontent.com/10169236/34887793-b39256e8-f802-11e7-8db1-d4adfdc1ac83.png)

Can  any one help me to configure it? 

/help wanted
