### ISSUE TITLE
third party resources not found, please enable API group extensions/v1beta1

### ISSUE THREAD

**Issue by nick4fake** [coreos/dex#1177]
````
time="2018-01-24T09:12:07Z" level=info msg="config using log level: debug"
time="2018-01-24T09:12:07Z" level=info msg="config issuer: https://login.-----.com"
time="2018-01-24T09:12:07Z" level=info msg="config connector: ldap"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="failed creating third party resources: <nil>"
time="2018-01-24T09:12:07Z" level=info msg="config storage: kubernetes"
time="2018-01-24T09:12:07Z" level=info msg="config skipping approval screen"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=info msg="keys expired, rotating"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:07Z" level=error msg="third party resources not found, please enable API group extensions/v1beta1"
time="2018-01-24T09:12:08Z" level=error msg="failed to rotate keys: not found"
time="2018-01-24T09:12:08Z" level=info msg="listening (http) on 0.0.0.0:80"
````

**Comment by nick4fake** [comment]
Rbac config:
````
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: dex
rules:
- apiGroups: ["oidc.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
  nonResourceURLs: []
- apiGroups: ["extensions"]
  resources: ["thirdpartyresources"]
  verbs: ["create"] # To manage its own resources identity must be able to create thirdpartyresources.
  nonResourceURLs: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex                 # Service account assigned to the dex pod.
  namespace: {{ .Release.Namespace }}  # The namespace dex is running in.

````
