### ISSUE TITLE
Issue with group membership claim

### ISSUE THREAD

**Issue by sujithvs74** [coreos/dex#1194]
I have configured dex with example app and I am able to use kubectl with generated tokens.  Issue I am facing is whenever I used token it gives me full access to all namespaces. I already added role and rolebinding to one namespace (with one AD group), that is not working here. I couldn't find any documentation on that here. Please check this issue.

Yaml used for role and role binding -
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role_kube_dev_admin
  namespace: poc
rules:
- apiGroups: ["*"]
  resources: [ "bindings", "events", "limitranges", "namespaces", "namespaces/status", "pods/log", "pods/status", "replicationcontrollers/status", "resourcequotas", "resourcequotas/status" ]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: [ "configmaps", "deployments.apps", "deployments.extensions", "deployments.apps/rollback", "deployments.extensions/rollback", "deployments.apps/scale", "deployments.extensions/scale", "endpoints", "ingresses.extensions", "pods", "pods/attach", "pods/exec", "pods/portforward", "pods/proxy", "replicationcontrollers", "replicationcontrollers/scale", "replicationcontrollers.extensions/scale", "secrets", "services", "services/proxy", "statefulsets.apps" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb_kube_dev_admin
  namespace: poc
subjects:
- kind: Group
  name: r_kube_dev_admin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: Mohan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role_kube_dev_admin
  apiGroup: rbac.authorization.k8s.io
```
