### ISSUE TITLE
Retrieve all groups of a user for LDAP connector?

### ISSUE THREAD

**Issue by eroji** [coreos/dex#1199]
Is there a way to configure the LDAP filter to retrieve all groups a user belong to? I tweaked the defaults around quite a bit but it's always showing `groups=[]`. My groups are in a 'Security Groups' OU with other OUs that any user can be a member of. 

Here is what I have that works for username but not groups:
```
    userSearch:
      baseDN: ou=Employees,dc=mydomain,dc=com
      filter: "(objectClass=user)"
      username: sAMAccountName
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: ou=Security Groups,dc=mydomain,dc=com
      filter: "(objectClass=group)"
      userAttr: DN
      groupAttr: member
      nameAttr: cn
```
