### ISSUE TITLE
missing required field "userSearch.baseDN" when run on kubernetes

### ISSUE THREAD

**Issue by zabykrinich** [coreos/dex#1235]
Hi, could you help me to understand why I run the problem with kubernetes DEX setup when real machine setup is OK please? 
I use the same config on a standalone DEX  and it seems to be working. Only one difference is a storage section. For real machine I use sql instead of kubernetes

I get following error from the POD: 
>Error: open ldap: ldap: missing required field "userSearch.baseDN"
>Usage:
>  dex serve [ config file ] [flags]
> Examples:
>dex serve config.yaml
> open ldap: ldap: missing required field "userSearch.baseDN"

Unfortunately nothing more I can't get. I check my config file in container and it seems to be OK. 

```
    issuer: https://myMaster.my.domain.com:5554/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
      https: 0.0.0.0:5554
      tlsCert: /etc/dex/tls/leaf.crt
      tlsKey: /etc/dex/tls/leaf.key
    telemetry:
      http: 0.0.0.0:5558
    expiry:
      signingKeys: "6h"
      idTokens: "24h"
    staticClients:
    - id: myapp
      redirectURIs:
      - 'http://myMaster.my.domain.com:5555/callback'
      name: 'My App'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: my.domain.com:3268
        insecureNoSSL: true
        insecureSkipVerify: true
        rootCA: /etc/dex/tls/root.pem
        bindDN: CN=myAdmin,OU=myBranch,DC=mySite,DC=my,DC=domain,DC=com
        bindPW: myAdminPassword
      userSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=user)"
        username: AccountName
        idAttr: AccountName
        emailAttr: mail
        nameAttr: AccountName
      groupSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=group)"
        userAttr: gName
        groupAttr: member
        nameAttr: name
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```
There is my yaml file to create the dex mapped on master node. I took it from examples. Only added secret named dex-secret from tls certificates 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex-internal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dex
    spec:

      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      containers:
      - image: quay.io/coreos/dex:v2.0.0-beta.1
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

        ports:
        - name: http
          containerPort: 5556
        - name: https
          containerPort: 5554

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls

      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: dex-secret
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex-internal
data:
  config.yaml: |
    issuer: https://myMaster.my.domain.com:5554/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
      https: 0.0.0.0:5554
      tlsCert: /etc/dex/tls/leaf.crt
      tlsKey: /etc/dex/tls/leaf.key
    telemetry:
      http: 0.0.0.0:5558
    expiry:
      signingKeys: "6h"
      idTokens: "24h"
    staticClients:
    - id: myapp
      redirectURIs:
      - 'http://myMaster.my.domain.com:5555/callback'
      name: 'My App'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: my.domain.com:3268
        insecureNoSSL: true
        insecureSkipVerify: true
        rootCA: /etc/dex/tls/root.pem
        bindDN: CN=myAdmin,OU=myBranch,DC=mySite,DC=my,DC=domain,DC=com
        bindPW: myAdminPassword
      userSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=user)"
        username: AccountName
        idAttr: AccountName
        emailAttr: mail
        nameAttr: AccountName
      groupSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=group)"
        userAttr: gName
        groupAttr: member
        nameAttr: name
    enablePasswordDB: true
    staticPasswords:
    - email: "admin@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex-internal
spec:
  type: NodePort
  ports:
  - name: dex
    port: 5554
    protocol: TCP
    targetPort: 5554
    nodePort: 32000
  selector:
    app: dex

```

**Comment by ericchiang** [comment]
This section of your config is formatted incorrectly.

```
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: my.domain.com:3268
        insecureNoSSL: true
        insecureSkipVerify: true
        rootCA: /etc/dex/tls/root.pem
        bindDN: CN=myAdmin,OU=myBranch,DC=mySite,DC=my,DC=domain,DC=com
        bindPW: myAdminPassword
      userSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=user)"
        username: AccountName
        idAttr: AccountName
        emailAttr: mail
        nameAttr: AccountName
      groupSearch:
        baseDN: DC=my,DC=domain,DC=com
        filter: "(objectClass=group)"
        userAttr: gName
        groupAttr: member
        nameAttr: name
```

It should be

```
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: my.domain.com:3268
        insecureNoSSL: true
        insecureSkipVerify: true
        rootCA: /etc/dex/tls/root.pem
        bindDN: CN=myAdmin,OU=myBranch,DC=mySite,DC=my,DC=domain,DC=com
        bindPW: myAdminPassword
        userSearch:
          baseDN: DC=my,DC=domain,DC=com
          filter: "(objectClass=user)"
          username: AccountName
          idAttr: AccountName
          emailAttr: mail
          nameAttr: AccountName
        groupSearch:
          baseDN: DC=my,DC=domain,DC=com
          filter: "(objectClass=group)"
          userAttr: gName
          groupAttr: member
          nameAttr: name
```
