### ISSUE TITLE
Encoding problem when updating auth request

### ISSUE THREAD

**Issue by hrzbrg** [coreos/dex#1239]
Hi,

I run Dex with LDAP and postgres as storage backend. From the logs I can see, that the login works, but updating the auth request in the DB fails. The mentioned `0xfc` character would correspond to an `ü`. Is this an issue with the returned data from LDAP? 

Log from Dex:

```
time="2018-05-22T12:40:49Z" level=info msg="performing ldap search ou=company,dc=example,dc=com sub (sAMAccountName=s.herzberg)" connector=LDAP
time="2018-05-22T12:40:49Z" level=info msg="username \"s.herzberg\" mapped to entry CN=Sebastian H,OU=City,OU=DE,OU=Users,OU=company,DC=example,DC=com" connector=LDAP
time="2018-05-22T12:40:49Z" level=info msg="performing ldap search ou=Groups,ou=mytaxi,dc=intapps,dc=it sub (&(objectClass=group)(member=CN=Sebastian H,OU=City,OU=DE,OU=Users,OU=company,DC=example,DC=com))" connector=LDAP
time="2018-05-22T12:40:49Z" level=error msg="Failed to finalize login: failed to update auth request: update auth request: pq: invalid byte sequence for encoding \"UTF8\": 0xfc"
```

Dex Config:

```
issuer: https://dex.example.com/dex
storage:
  type: postgres
  config:
    host: dex-db.example.com
    database: dex
    user: dex
    password: 123456
    ssl:
      mode: require
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text

connectors:
  - type: ldap
    id: ldap
    name: LDAP
    config:
      host: ldap.example.com:636
      insecureNoSSL: false
      insecureSkipVerify: false
      bindDN: 'cn=bind,ou=Services,ou=cmpany,dc=example,dc=com'
      bindPW: 123456
      userSearch:
        baseDN: ou=company,dc=example,dc=com
        username: sAMAccountName
        idAttr: objectGUID
        emailAttr: mail
        nameAttr: sAMAccountName
      groupSearch:
        baseDN: ou=Groups,ou=company,dc=example,dc=com
        filter: "(objectClass=group)"
        userAttr: DN
        groupAttr: member
        nameAttr: name
oauth2:
  skipApprovalScreen: true
staticClients:
- id: sandbox-loginapp
  redirectURIs:
  - 'https://login.sandbox.example.com/callback'
  name: 'Sandbox Login'
  secret: secrettoken

```
