### ISSUE TITLE
LDAP connector  problem

### ISSUE THREAD

**Issue by antonionappi88** [coreos/dex#1247]
Hello, 
I tried to setup DEX with LDAP connector. 

I used a simple login app. I'm able to get a token and the kubeconfig file.
So I created this `ClusterRole` : 

```
kind: ClusterRole                         
apiVersion: rbac.authorization.k8s.io/v1  
metadata:                                 
  name: pod-reader                        
rules:                                    
- apiGroups: [""]                         
  resources: ["pods"]                     
  verbs: ["get", "watch", "list","delete"]
---                                       
```

And after added the rolebinding : 

```
kubectl create rolebinding pod-reader-binding --clusterrole=pod-reader --user=myuser --namespace=myns
```

But when I try to get the list of pods, it returns me : 

```
Error from server (Forbidden): pods is forbidden: User "https://DEX_HOST/dex#myuser" cannot list pods in the namespace "myns"
```

Even If i setup debug logging mode, they are not really helpful.

Do you have any suggestion ?

Thank you in advance!
Antonio
