### ISSUE TITLE
contrib/k8s: Ingress controller requires host port 8080, a common port for the apiserver

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#513]
The ingress controller we link to in the contrib/k8s doc has a small bit in the spec:

```yaml
        # we expose 8080 to access nginx stats in url /nginx-status
        # this is optional
        - containerPort: 8080
          hostPort: 8080
```

However this can cause contention if anything else is already listening on this port. A common case is the API Server since that's the (non-configurable) default for minikube and our default for coreos-kubernetes.

Fork the ingress spec for our repo and take this bit out.
