### ISSUE TITLE
cmd/dex: expose IDTokensValidFor and RotateKeysAfter server options in config

### ISSUE THREAD

**Issue by ericchiang** [coreos/dex#660]
Though those names suck. Perhaps in the config it could look like:

```yaml
expiry:
    idTokens: 48h
    signingKeys: 12h
```

cc @robszumski
