### ISSUE TITLE
connector/github: grab membership of orgs and/or teams instead of just teams

### ISSUE THREAD

**Issue by danielfm** [coreos/dex#691]
After reading the quick start guide (and the source code, since the documentation at this point is lacking), I managed to get the GitHub connector to work with the following configuration:

```yaml
# ./examples/config-dev.yaml
connectors:
- type: github
  id: github
  name: github
  config:
    redirectURI: http://127.0.0.1:5556/dex/callback
    clientID: ***
    clientSecret: ***
    org: my-org
```

With this, I can start the dex server and the example openid client and complete the authentication workflow:

```sh
# First terminal window
./bin/dex serve examples/config-dev.yaml

# Second terminal window
./bin/example-app
```

The only thing I missed was the ability to only authorize users from some organization. I noticed the source code has the concept of groups, but I tried to set the `org` configuration key but it doesn't seem to do anything.

Am I doing something wrong?
