### ISSUE TITLE
Refresh token not working with LDAP connector

### ISSUE THREAD

**Issue by blakebarnett** [coreos/dex#786]
Dex version: 2.0.2
Kubernetes version: 1.5.2

It seems https://github.com/coreos/dex/blob/fe93f60af4ab1b84371d331f40504a129f7ca86b/server/handlers.go#L749 is empty when using LDAP.  

Using regular tokens works, but we'd like to be able to use short-lived tokens with automatic refresh.

I get this in the dex logs when I attempt it:
`dex time="2017-01-25T01:19:28Z" level=error msg="connector ID not found: \"\""`

kubectl config for my user:
```yaml- name: stage.us-west-2.aws.k8s-blake.barnett
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: REDACTED
        id-token: REDACTED
        idp-certificate-authority: /path/to/ca.crt
        idp-issuer-url: https://dex.stage.us-west-2.aws.k8s:5556
        refresh-token: REDACTED
      name: oidc
```
