### ISSUE TITLE
ID-Token does not contain email

### ISSUE THREAD

**Issue by maltevogl** [coreos/dex#837]
I am integrating Dex with Jupyter HUB. Authentification is via an external OpenID Connect Server based on SpringSecurity (mitre) and Github. Both connectors provide access tokens as expected. However, the ID-Token does not contain the email-address. 

The scopes are openid, email, profile and the claim "email_verified" is contained in the ID token. So from the source code it seems that for both connectors, the email send by the IdPs is empty or treated as empty, cf. [this part of oauth2.go](https://github.com/coreos/dex/blob/master/server/oauth2.go#L242)  

For the Github connector, there is an additional field "name" with the username in the access token, which is absent for the oidc connector, where the user_id is contained in the "sub" field. 

How is the flow for these additional informations in the ID token? What am I missing here?

**Comment by rithujohn191** [comment]
Hi @maltevogl,

Could you please provide more clarification on how how you are performing the authentication? Providing the Dex ConfigMap would be helpful. If I understand correctly you are trying to use the github connector with dex and the id-token retrieved does not have an email field? 

Running the example-app as documented (here)[https://github.com/coreos/dex/blob/master/Documentation/getting-started.md] will give you a better idea of the code flow. You can modify the (ConfigMap)[https://github.com/coreos/dex/blob/master/examples/config-dev.yaml] for the example to include the github connector.

**Comment by maltevogl** [comment]
Hi @rithujohn191 

I adapted the example config file,  the minimal modification for reproducing this issue with the example-app is to add the following to the connector field in config-dev.yaml:
```
- type: github
  id: github
  name: Github
  config:
    clientID: generated_id
    clientSecret: generated_secret
    redirectURI: http://127.0.0.1:5556/dex/callback
```
Running the example dex server ```./bin/dex serve example/config-dev.yaml``` and the example-app ```./bin/example-app ``` , one can authentify via GitHub. However, the decoded ID-token in the example-app then contains the following claims
```
 Claims:
{
  "iss": "http://127.0.0.1:5556/dex",
  "sub": (base64-encoded: github_userID + connector ID),
  "aud": "example-app",
  "exp": 1488962701,
  "iat": 1488876301,
  "at_hash": "ZMvfKlY8Gffp50VdNqCx8A",
  "email_verified": true,
  "name": "github_username"
}
```
So parts of the scopes  "user:email" are received, because the "name" and "email_verified" fields are there. But additional information, like the actual email, are missing.

Adding a connector to a third-party OIDC IdP, based on [Mitre-Connect](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server), 
```
- type: oidc
  id: mitre
  name: MitreOIDC
  config:
    issuer: https://mitre_ip/openid/
    clientID: redacted
    clientSecret: redacted
    redirectURI: http://127.0.0.1:5556/dex/callback
```
returns similar claims, with the "name"  field missing. 
This connector should return "profile" and "email" scopes, which from the Mitre-Server side include the claims sub, name, family_name, preferred_username, given_name, email, and email_verified. 
Only the "email_verified" claim and a sub field are included in the returned ID-token.

So, my question is if the email field is empty by design, or if I am missing options in the config part for the connectors.
