### ISSUE TITLE
LDAP tls: handshake failure

### ISSUE THREAD

**Issue by yawboateng** [coreos/dex#845]
having problems trying to get dex ldap connector to work with an ldap server that uses a selfsigned cert.

error:
`2017-03-11T05:40:20.418894746Z time="2017-03-11T05:40:20Z" level=error msg="Failed to login user: failed to connect: LDAP Result Code 200 \"\": remote error: tls: handshake failure" `

Before starting dex, i try to run an openssl command to get the root ca of the ldap server.

`openssl s_client -showcerts -connect ${LDAP_HOST}:636 </dev/null | openssl x509 -outform PEM > /etc/dex/cacert.pem; dex serve /etc/dex/cfg/config.yaml`

and in my config.yaml I have:

```
issuer: https://dex.example.com:5556
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key

connectors:
- type: ldap
  id: ldap
  name: ldap
  config:
    host: ldapHost
    rootCA: /etc/dex/cacert.pem
    bindDN: bindDN
    bindPW: bindPW
    userSearch:
      baseDN: ldapBaseDN
      username: uid
      idAttr: uid
      emailAttr: email
      nameAttr: cn
    groupSearch:
      baseDN: ldapBaseDN
      filter: filter
      userAttr: uid
      groupAttr: group
      nameAttr: cn
oauth2:
  skipApprovalScreen: true

staticClients:
- id: client-id
  redirectURIs:
    - https://client.example.com/callback
  name: clientName
  secret: clientSec
enablePasswordDB: false
```
I've also tried adding rootCAData key and setting it to the path of the ldap key (/etc/dex/cacert.pem) but i get an error: 

`error parse config file etc/dex/cfg/config.yaml: error unmarshaling JSON: parse connector config: illegal base64 data at input byte 15`

what im I missing here, is there any other configuration i need to set to get this to work?
