### ISSUE TITLE
ldap connector groups

### ISSUE THREAD

**Issue by yawboateng** [coreos/dex#856]
in my ldap server, a single user can be under multiple groups but for some reason only the first group shown in the list when i run ldapsearch command is being returned by dex to my oauth2 client.

oauth2-client:
```
{
  "at_hash": "vSd0v1G9KcmhXTWsbXIxzA", 
  "aud": "<cleintID>", 
  "email": "<email>, 
  "email_verified": true, 
  "exp": 1489767595, 
  "groups": [
    "cn=group1,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME"
  ], 
  "iat": 1489681195, 
  "iss": "<dexServerHost>", 
  "name": "<userName>", 
  "sub": "CghiYWJvYXRlbhIEbGRhcA"
}
```

config.yaml:
```
issuer: https://dex.example.com:5556
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key

connectors:
- type: ldap
  id: ldap
  name: ldap
  config:
    host: ldapHost
    rootCA: /etc/dex/cacert.pem
    bindDN: bindDN
    bindPW: bindPW
    userSearch:
      baseDN: ldapBaseDN
      filter: "(objectclass=person)"
      username: uid
      idAttr: uid
      emailAttr: email
      nameAttr: cn
    groupSearch:
      baseDN: ldapBaseDN
      filter: "(objectclass=person)"
      userAttr: uid
      groupAttr: uid
      nameAttr: memberOf
oauth2:
  skipApprovalScreen: true

staticClients:
- id: client-id
  redirectURIs:
    - https://client.example.com/callback
  name: clientName
  secret: clientSec
enablePasswordDB: false
```

**Comment by ericchiang** [comment]
```
     groupSearch:
      baseDN: ldapBaseDN
      filter: "(objectclass=person)"
      userAttr: uid
      groupAttr: uid
      nameAttr: member
```

Your filter here seems odd.

I don't know how much help we can be of without seeing what LDAP search results look like or what query you're providing.

**Comment by yawboateng** [comment]
sorry nameAttr value is memeberOf not memeber

I used wireshark to capture the packets
heres how the SearchRequest looks like:
```
baseObject: ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
scope: wholeSubtree (2)
derefAliases: neverDerfAliases (0)
sizeLimit: 0
timeLimit: 0
typesOnly: False
Filter: (&(objectclass=person)(uid=yawboateng))
attributes: 1 item
    AttributeDescription: memberOf
```
searchResEntry:
```
baseObject: uid=yawboateng,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
protocolOp: searchResEntry (4)
    searchResEntry: 
        objectName: uid=yawboateng,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
    attributes: 1 item
        PartialAttributeList item memberOf
             type: memberOf
             vals: 5 items
                 AttributeValue: cn=group1,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
                 AttributeValue: cn=group2,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
                 AttributeValue: cn=group3,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
                 AttributeValue: cn=group4,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
                 AttributeValue: cn=group5,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
```

ldapsearch:

```
dn:  uid=yawboateng,ou=users,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
javaClassName: java.util.properties
sn: FirstName
uidnumber: 120334
gidnumber: 100394
uid: yawboateng
objectclass: person
objectclass: javaObject
objectclass: javaSerializedObject
objectclass: top
email: user@test.com
javaClassNames: java.util.Properties
javaClassNames: java.util.Hashtable
javaClassNames: java.util.Dictionary
javaClassNames: java.lang.Object
javaClassNames: java.util.Map
javaClassNames: java.lang.Cloneable
javaClassNames: java.io.Serializable
cn: FirstName LastName
memeberOf: cn=group1,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
memeberOf: cn=group2,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
memeberOf: cn=group3,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
memeberOf: cn=group4,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
memeberOf: cn=group5,ou=groups,ou=ouNAME,ou=ouNAME,ou=ouNAME,ou=ouNAME,dc=dcNAME
```

**Comment by yawboateng** [comment]
Fixed with:
```
groupSearch:
      baseDN: ldapBaseDN
      userAttr: DN
      groupAttr: member
      nameAttr: DN
```
