### ISSUE TITLE
garbage collection run errror

### ISSUE THREAD

**Issue by yawboateng** [coreos/dex#890]
Hello,
im running dex in kubernetes and seeing the following errors in the logs - not sure what exactly is the cause...anywhere I can get more info on this?

2017-04-04T14:56:35.299846286Z time="2017-04-04T14:56:35Z" level=error msg="garbage collection run, delete auth requests=0, auth codes=1" 
2017-04-04T15:21:35.356607004Z time="2017-04-04T15:21:35Z" level=error msg="garbage collection run, delete auth requests=1, auth codes=0" 
2017-04-04T16:01:35.467104511Z time="2017-04-04T16:01:35Z" level=error msg="garbage collection run, delete auth requests=2, auth codes=0"

**Comment by ericchiang** [comment]
@yawboateng it looks like we're incorrectly marking this as an error when it should be an "info" level message. @rithujohn191 can you send a fix for that?

**Comment by yawboateng** [comment]
Also seeing:


```
2017-04-04T17:06:05.273298812Z time="2017-04-04T17:06:05Z" level=info msg="keys expired, rotating" 
2017-04-04T17:06:05.952820941Z time="2017-04-04T17:06:05Z" level=error msg="failed to rotate keys: keys already rotated" 

```
shouldnt the keys already rotated also be logged as info?

**Comment by rithujohn191** [comment]
@yawboateng when exactly did you observe the error message (was it for a particular use case)? Are you running a single or multiple instances of Dex?

**Comment by yawboateng** [comment]
Im running 3 replicas of dex in kubernetes for an HA set up. should I be running only a single replica at a time? 

and kubectl logs shows:

```
time="2017-04-04T14:56:35Z" level=error msg="garbage collection run, delete auth requests=0, auth codes=1" 
time="2017-04-04T15:21:35Z" level=error msg="garbage collection run, delete auth requests=1, auth codes=0" 
time="2017-04-04T16:01:35Z" level=error msg="garbage collection run, delete auth requests=2, auth codes=0" 
time="2017-04-04T16:21:35Z" level=error msg="garbage collection run, delete auth requests=2, auth codes=0" 
time="2017-04-04T17:06:05Z" level=info msg="keys expired, rotating" 
time="2017-04-04T17:06:05Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-04T19:41:36Z" level=error msg="garbage collection run, delete auth requests=2, auth codes=0" 
time="2017-04-04T19:46:36Z" level=error msg="garbage collection run, delete auth requests=0, auth codes=1" 
time="2017-04-04T20:16:36Z" level=error msg="garbage collection run, delete auth requests=3, auth codes=0" 
time="2017-04-04T20:26:36Z" level=error msg="garbage collection run, delete auth requests=1, auth codes=0" 
time="2017-04-04T23:06:06Z" level=info msg="keys expired, rotating" 
time="2017-04-04T23:06:07Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-05T11:06:07Z" level=info msg="keys expired, rotating" 
time="2017-04-05T11:06:08Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-05T17:06:08Z" level=info msg="keys expired, rotating" 
time="2017-04-05T17:06:08Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-05T23:06:08Z" level=info msg="keys expired, rotating" 
time="2017-04-05T23:06:09Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-06T05:06:09Z" level=info msg="keys expired, rotating" 
time="2017-04-06T05:06:10Z" level=error msg="failed to rotate keys: keys already rotated" 
time="2017-04-06T17:06:10Z" level=info msg="keys expired, rotating" 
time="2017-04-06T17:06:11Z" level=info msg="keys rotated, next rotation: 2017-04-06 23:06:11.166543321 +0000 UTC" 
```

```
issuer: https://dex.com:5556
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key

connectors:
- type: ldap
  id: ldap
  name: ccsso
  config:
    <ldap config here>
oauth2:
  skipApprovalScreen: true

staticClients:
- id: clientid1
  redirectURIs:
    - calbackurl1
- id: clientid2
  redirectURIs:
    - calbackurl2
enablePasswordDB: false

expiry:
  signingKeys: "6h"
  idTokens: "24h"
```
