### ISSUE TITLE
ldap insecureSkipVerify - remote error: tls: handshake failure

### ISSUE THREAD

**Issue by yawboateng** [coreos/dex#907]
running dex with ldap insecureSkipVerify set to true returns the error below:

017-04-12T14:54:26.707945506Z time="2017-04-12T14:54:26Z" level=error msg="Failed to login user: failed to connect: LDAP Result Code 200 \"\": remote error: tls: handshake failure"

setting the flag to false also returns the same error, any help on what might be causing this? and is it possible to get more information in the logs?

```
issuer: https://dex.example.com:5556
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
  #tlsCert: /etc/dex/tls/tls.crt
  #tlsKey: /etc/dex/tls/tls.key

connectors:
- type: ldap
  id: ldap
  name: ldap
  config:
    host: ldapHost:636
    rootCA: /etc/dex/cacert.pem
    insecureSkipVerify: true
    bindDN: bindDN
    bindPW: bindPW
    userSearch:
      baseDN: ldapBaseDN
      username: uid
      idAttr: uid
      emailAttr: email

      nameAttr: cn
    groupSearch:
      baseDN: ldapBaseDN
      filter: filter
      userAttr: uid
      groupAttr: group
      nameAttr: cn
oauth2:
  skipApprovalScreen: true

staticClients:
- id: client-id
  redirectURIs:
    - https://client.example.com/callback
  name: clientName
  secret: clientSec
enablePasswordDB: false

```
