### ISSUE TITLE
tokens: Refresh never occurs on custom (LDAP-group-based) bindings

### ISSUE THREAD

**Issue by joshrosso** [coreos/dex#940]
## Impact

dex version: `quay.io/coreos/dex:v2.2.4`
k8s version: [`v1.5.3+coreos.0`, `v1.5.5+coreos.0`]
kubectl version: [`1.5.5`,`1.6.1`]

## Behavior

Ever 24 hours, operations enabled by our [non-tectonic created] cluster role bindings (CRB) expire requiring us to re-gen a kube-config, in our case, through Tectonic console. 

For example, we have the following CRB setup.

```yaml
$ kubectl get -o yaml clusterrolebindings logview

apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
 # metadata removed for brevity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logview
subjects:
- kind: Group
  name: our-developers-group
``` 

The corresponding role is as follows.

```yaml
$ kubectl get -o yaml clusterrole logview

apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  # metadata removed for brevity
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/log
  verbs:
  - '*'
```

After 24 hours, developers part of `our-developers-group` will receive the following message via `kubectl`.

```bash
$ kubectl logs -n kube-system $SOME_POD_HERE

Error from server (Forbidden): the server does not allow access to the requested resource (get pods $SOME_POD_HERE)
```

The only remedy is to then regenerate a kube-config.

Lastly, it's important to note that some operations still work, e.g. `get pods`, etc. Perhaps this is due to some existing `system:*` based rolebindings put in place...but we're not sure.
