### ISSUE TITLE
github id provider

### ISSUE THREAD

**Issue by zxdzxd** [coreos/dex#947]
@ericchiang can you give detailed steps on how to implement github using dex
i am getting certain error as "unable to connect github"

**Comment by zxdzxd** [comment]
![screenshot from 2017-05-15 11 59 17](https://cloud.githubusercontent.com/assets/25072819/26045180/8eb5a376-3966-11e7-841c-25ff93aa5aa5.png)

**Comment by zxdzxd** [comment]
time="2017-05-15T06:24:10Z" level=error msg="Invalid 'state' parameter provided: not found" 
time="2017-05-15T06:25:17Z" level=error msg="Invalid 'state' parameter provided: not found"

these are errors

**Comment by zxdzxd** [comment]
```
 level=error msg="Invalid 'state' parameter provided: not found" 
```

```
# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: http://127.0.0.1:5556/dex

# The storage configuration determines where dex stores its state. Supported
# options include SQL flavors and Kubernetes third party resources.
#
# See the storage document at Documentation/storage.md for further information.
storage:
  type: sqlite3
  config:
    file: examples/dex.db

# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556
  # Uncomment for HTTPS options.
#   https: 127.0.0.1:5555
#   tlsCert: /etc/dex/server.crt
#   tlsKey: /etc/dex/server.key

# Uncomment this block to enable the gRPC API. This values MUST be different
# from the HTTP endpoints.
# grpc:
#  addr: 127.0.0.1:5557
#  tlsCert: examples/grpc-client/server.crt
# tlsKey: examples/grpc-client/server.key
#  tlsClientCA: /etc/dex/client.crt

# Uncomment this block to enable configuration for the expiration time durations.
# expiry:
#   signingKeys: "6h"
#   idTokens: "24h"

# Options for controlling the logger.
# logger:
#   level: "debug"
#   format: "text" # can also be "json"

# Instead of reading from an external storage, use this list of clients.
#
# If this option isn't chosen clients may be added through the gRPC API.
staticClients:
- id: 6c0971e3c5016f020e0f
  redirectURIs:
  - 'http://127.0.0.1:5556/dex/callback'
  name: 'Github'
  secret: 5dd8069b23820aaad1afb6c215f6eb5cd72f33c2

connectors:
#- type: mockCallback
#  id: mock
#  name: Example
 - type: github
   id: github
   name: Github
   config:
     issuer: http://127.0.0.1:5556/dex
#     # Connector config values starting with a "$" will read from the environment.
     clientID: 6c0971e3c5016f020e0f
     clientSecret: 5dd8069b23820aaad1afb6c215f6eb5cd72f33c2
     redirectURI: http://127.0.0.1:5556/dex/callback

# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: true

# A static list of passwords to login the end user. By identifying here, dex
# won't look in its underlying storage for passwords.
#
# If this option isn't chosen users may be added through the gRPC API.
#staticPasswords:
#- email: "admin@example.com"
  # bcrypt hash of the string "password"
#  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
#  username: "admin"
#  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```
this is config-dev.yaml file
is the config file correct ?
how can i remove above error ?

**Comment by rithujohn191** [comment]
@zxdzxd  Please specify which version of dex you are using.

**Comment by munna-bhai** [comment]
dex master

**Comment by zxdzxd** [comment]
dex master

**Comment by zxdzxd** [comment]
@rithujohn191 i am getting similar error as in issue #944 
https://github.com/coreos/dex/issues/944

while i am working to implement it for github using sqlite 3

**Comment by rithujohn191** [comment]
@zxdzxd are you trying to follow the [getting started docs](https://github.com/coreos/dex/blob/master/Documentation/getting-started.md) and implement the example app? In that case the values under `staticClients` is wrong. You seem to have provided the GitHub client credentials. It should be changed to the following:

```
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
```
You can find the source code of the example app here: https://github.com/coreos/dex/tree/master/cmd/example-app

**Comment by zxdzxd** [comment]
thank you for response @rithujohn191 
github id provider is working now 

but when similar configuration change i did for Gitlab 

i get following error
```
time="2017-05-18T10:37:53Z" level=error msg="Failed to authenticate: gitlab: failed to get token: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.\"}"
```
```
Failed to return user's identity.
```
it is generated from here
https://github.com/coreos/dex/blob/master/server/handlers.go#L379

my config-dev.yaml codes for connector 

```
connectors:
#- type: mockCallback
#  id: mock
#  name: Example
 - type: gitlab
   id: gitlab
   name: Gitlab
   config:
     baseURL: https://www.gitlab.com
     issuer: http://127.0.0.1:5556/dex
#     # Connector config values starting with a "$" will read from the environment.
     clientID: gitlab client id
     clientSecret: gitlab client secret   
     redirectURI: http://127.0.0.1:5556/dex/callback

````
please help me solve the error

![screenshot from 2017-05-18 16 22 40](https://cloud.githubusercontent.com/assets/25072819/26199066/4b6372f6-3be6-11e7-86ff-ab38357868b4.png)

**Comment by tfluehmann** [comment]
+1 I have the same issue with google
go_projects/src/github.com/coreos/dex$ bin/dex version
dex Version: 15242a86b83058d0b3409a304320878006e1c3c6
Go Version: go1.8.3
Go OS/ARCH: darwin amd64

**Comment by rithujohn191** [comment]
@tfluehmann have you followed the instructions [here](https://github.com/coreos/dex/blob/master/Documentation/gitlab-connector.md#configuration) to register your app with gitlab? Do the callback URLs match?

**Comment by tfluehmann** [comment]
@rithujohn191 No, I follwed the instructions here: https://github.com/coreos/dex/blob/master/Documentation/oidc-connector.md
But in the google interface I've whitelisted the callback url http://127.0.0.1:8080/dex/callback.
The downloaded JSON from google looks like this:
```
{"web":
	{"client_id":"xyz",
	"project_id":"eighth-beacon-100622",
        "auth_uri":"https://accounts.google.com/o/oauth2/auth",
        "token_uri":"https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
        "client_secret":"xyz",
        "redirect_uris":["http://127.0.0.1:8080/dex/callback"],
        "javascript_origins":["http://localhost","http://127.0.0.1"]
        }
}
```

**Comment by so0k** [comment]
might wanna cycle your github oauth app credentials

**Comment by derekjwilliams** [comment]
I'm also seeing the same on Gitlab:

My connector configuration for gitlab in my dex configuration:

`- type: gitlab
  id: gitlab
  name: Gitlab
  config:
    baseURL: https://www.gitlab.com
    clientID: $GITLAB_CLIENT_ID
    clientSecret: $GITLAB_SECRET
    redirectURI: http://127.0.0.1:5556/dex/callback    
`
Gitlab configuration

Application Id: [GITLAB_CLIENT_ID]
Secret: [GITLAB_SECRET]
Callback url: http://127.0.0.1:5556/dex/callback
Scopes:
api (Access your API)
read_user (Read user information)
read_registry (Read Registry)
openid (Authenticate using OpenID Connect)

**Comment by derekjwilliams** [comment]
```
- type: gitlab
  id: gitlab
  name: Gitlab
  config:
    baseURL: https://www.gitlab.com
    clientID: 257b7813a3f9d13a5a72cc811f90ee0daad8862c5048e8faff0ff246d86b2952
    clientSecret: ed7f70dadf8b0f28070d8c6347e7d45dfc0a425881916eb333d107bc967ba3ad
    redirectURI: http://127.0.0.1:5556/dex/callback
```
