### ISSUE TITLE
Active Directory LDAP

### ISSUE THREAD

**Issue by matthubb** [coreos/dex#950]
I've made modifications to `ldap.go` to make use of Active Directory features.

Specifically:
- Checking that the `userAccountControl` attribute on the user entry doesn't have the `ADS_UF_ACCOUNTDISABLE` flag set.
- Reading `tokenGroups` attributes by searching at the base of the userDN, which returns the `objectSid` for groups and then looking up the group names by these objectSids. `tokenGroups` should represent flattened group memberships.

Would you be interested in these modifications?

I'm not sure how to fit them in to the connector configuration. A brand new connector would be duplicating most of the ldap connector. The `userAccountControl`  check could be a boolean configuration item under `userSearch`. The AD group lookup is a new `groups` function, which could also be selected based on a boolean configuration item, this time under `groupSearch`.

**Comment by rithujohn191** [comment]
Thank you for reaching out @matthubb. We would love to review what you have. For now you could just add it as an extension to the LDAP connector itself and enable active directory specific features via flags in the config struct.

I am still a little unclear how these additions are different from specifying them in the LDAP query itself. Might make more sense once I get a look at the code

**Comment by publicvirtualvoid** [comment]
@matthubb I'd love to take a look as well, do you mind sharing?

**Comment by matthubb** [comment]
Yes, I will do. Sorry been rather busy and it needs a little tidy up.

**Comment by ericchiang** [comment]
> Checking that the userAccountControl attribute on the user entry doesn't have the ADS_UF_ACCOUNTDISABLE flag set.

Can you not express that as part of your LDAP filter?

> Reading tokenGroups attributes by searching at the base of the userDN, which returns the objectSid for groups and then looking up the group names by these objectSids. tokenGroups should represent flattened group memberships.

You can already customize a search based on user DN.

```yaml
    # Group search queries for groups given a user entry.
    groupSearch:
      # BaseDN to start the search from. It will translate to the query
      # "(&(objectClass=group)(member=<user DN>))".
      baseDN: cn=groups,dc=freeipa,dc=example,dc=com
      # Optional filter to apply when searching the directory.
      filter: "(objectClass=group)"

      userAttr: DN # Use "DN" here not "uid"
      groupAttr: member

      nameAttr: name
```
