### ISSUE TITLE
LDAP groups from Active Directory

### ISSUE THREAD

**Issue by publicvirtualvoid** [coreos/dex#982]
It seems that the LDAP connector can't currently pull group memberships from Active Directory LDAP servers because it assumes "member" fields to be populated with Uids.
In order for this to work, I must be able to set this to be the user DN instead.

It looks like someone has already made these changes but the code was never made available (#950)

I'm not very experienced in Go, but it seems like this would be a pretty straightforward change. 
From what I can determine, on line 480 in ldap.go:
`for _, attr := range getAttrs(user, c.GroupSearch.UserAttr) {`
should be
`for _, attr := range getAttrs(user, c.GroupSearch.BaseDN) {`

This doesn't seem to work, however.

Could someone point me in the right direction?

**Comment by manuvaldi** [comment]
+1

**Comment by ericchiang** [comment]
You can already do this. E.g. the following config would match any entry with `member=<user DN>`.

```
    # Group search queries for groups given a user entry.
    groupSearch:
      # BaseDN to start the search from. It will translate to the query
      # "(&(objectClass=group)(member=<user DN>))".
      baseDN: cn=groups,dc=freeipa,dc=example,dc=com
      # Optional filter to apply when searching the directory.
      filter: "(objectClass=group)"

      userAttr: DN # Use "DN" here not "uid"
      groupAttr: member

      nameAttr: name
```

Closing. Please let me know if I've misunderstood.
